server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/searchengine
    username: root
    password: Samara2020-
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
  user-agent: HeliontSearchBot/1.0
  referrer: http://www.google.com
  delay-between-requests: 500
  max-pages-per-site: 1000
logging:
  level:
    searchengine: TRACE
    org.springframework.web: DEBUG
    org.hibernate: ERROR